//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INB374.warehouseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="warehouseService.warehouseWebServiceSoap")]
    public interface warehouseWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name productCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWaitTime", ReplyAction="*")]
        INB374.warehouseService.getWaitTimeResponse getWaitTime(INB374.warehouseService.getWaitTimeRequest request);
        
        // CODEGEN: Generating message contract since element name orderStockResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/orderStock", ReplyAction="*")]
        INB374.warehouseService.orderStockResponse orderStock(INB374.warehouseService.orderStockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWaitTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWaitTime", Namespace="http://tempuri.org/", Order=0)]
        public INB374.warehouseService.getWaitTimeRequestBody Body;
        
        public getWaitTimeRequest() {
        }
        
        public getWaitTimeRequest(INB374.warehouseService.getWaitTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWaitTimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productCode;
        
        public getWaitTimeRequestBody() {
        }
        
        public getWaitTimeRequestBody(string productCode) {
            this.productCode = productCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWaitTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWaitTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public INB374.warehouseService.getWaitTimeResponseBody Body;
        
        public getWaitTimeResponse() {
        }
        
        public getWaitTimeResponse(INB374.warehouseService.getWaitTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWaitTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getWaitTimeResult;
        
        public getWaitTimeResponseBody() {
        }
        
        public getWaitTimeResponseBody(string getWaitTimeResult) {
            this.getWaitTimeResult = getWaitTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orderStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orderStock", Namespace="http://tempuri.org/", Order=0)]
        public INB374.warehouseService.orderStockRequestBody Body;
        
        public orderStockRequest() {
        }
        
        public orderStockRequest(INB374.warehouseService.orderStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class orderStockRequestBody {
        
        public orderStockRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orderStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orderStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public INB374.warehouseService.orderStockResponseBody Body;
        
        public orderStockResponse() {
        }
        
        public orderStockResponse(INB374.warehouseService.orderStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class orderStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderStockResult;
        
        public orderStockResponseBody() {
        }
        
        public orderStockResponseBody(string orderStockResult) {
            this.orderStockResult = orderStockResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface warehouseWebServiceSoapChannel : INB374.warehouseService.warehouseWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class warehouseWebServiceSoapClient : System.ServiceModel.ClientBase<INB374.warehouseService.warehouseWebServiceSoap>, INB374.warehouseService.warehouseWebServiceSoap {
        
        public warehouseWebServiceSoapClient() {
        }
        
        public warehouseWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public warehouseWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public warehouseWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public warehouseWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INB374.warehouseService.getWaitTimeResponse INB374.warehouseService.warehouseWebServiceSoap.getWaitTime(INB374.warehouseService.getWaitTimeRequest request) {
            return base.Channel.getWaitTime(request);
        }
        
        public string getWaitTime(string productCode) {
            INB374.warehouseService.getWaitTimeRequest inValue = new INB374.warehouseService.getWaitTimeRequest();
            inValue.Body = new INB374.warehouseService.getWaitTimeRequestBody();
            inValue.Body.productCode = productCode;
            INB374.warehouseService.getWaitTimeResponse retVal = ((INB374.warehouseService.warehouseWebServiceSoap)(this)).getWaitTime(inValue);
            return retVal.Body.getWaitTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INB374.warehouseService.orderStockResponse INB374.warehouseService.warehouseWebServiceSoap.orderStock(INB374.warehouseService.orderStockRequest request) {
            return base.Channel.orderStock(request);
        }
        
        public string orderStock() {
            INB374.warehouseService.orderStockRequest inValue = new INB374.warehouseService.orderStockRequest();
            inValue.Body = new INB374.warehouseService.orderStockRequestBody();
            INB374.warehouseService.orderStockResponse retVal = ((INB374.warehouseService.warehouseWebServiceSoap)(this)).orderStock(inValue);
            return retVal.Body.orderStockResult;
        }
    }
}
