//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INB374.warehouseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="warehouseService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name productCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWaitTime", ReplyAction="*")]
        INB374.warehouseService.getWaitTimeResponse getWaitTime(INB374.warehouseService.getWaitTimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWaitTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWaitTime", Namespace="http://tempuri.org/", Order=0)]
        public INB374.warehouseService.getWaitTimeRequestBody Body;
        
        public getWaitTimeRequest() {
        }
        
        public getWaitTimeRequest(INB374.warehouseService.getWaitTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWaitTimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productCode;
        
        public getWaitTimeRequestBody() {
        }
        
        public getWaitTimeRequestBody(string productCode) {
            this.productCode = productCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWaitTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWaitTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public INB374.warehouseService.getWaitTimeResponseBody Body;
        
        public getWaitTimeResponse() {
        }
        
        public getWaitTimeResponse(INB374.warehouseService.getWaitTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWaitTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getWaitTimeResult;
        
        public getWaitTimeResponseBody() {
        }
        
        public getWaitTimeResponseBody(string getWaitTimeResult) {
            this.getWaitTimeResult = getWaitTimeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : INB374.warehouseService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<INB374.warehouseService.WebService1Soap>, INB374.warehouseService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INB374.warehouseService.getWaitTimeResponse INB374.warehouseService.WebService1Soap.getWaitTime(INB374.warehouseService.getWaitTimeRequest request) {
            return base.Channel.getWaitTime(request);
        }
        
        public string getWaitTime(string productCode) {
            INB374.warehouseService.getWaitTimeRequest inValue = new INB374.warehouseService.getWaitTimeRequest();
            inValue.Body = new INB374.warehouseService.getWaitTimeRequestBody();
            inValue.Body.productCode = productCode;
            INB374.warehouseService.getWaitTimeResponse retVal = ((INB374.warehouseService.WebService1Soap)(this)).getWaitTime(inValue);
            return retVal.Body.getWaitTimeResult;
        }
    }
}
