//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warehouseService.supplierService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderQueue", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderQueue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.productCodeField, value) != true)) {
                    this.productCodeField = value;
                    this.RaisePropertyChanged("productCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string quantityInStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msrpField;
        
        private bool inStoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                if ((object.ReferenceEquals(this.productNameField, value) != true)) {
                    this.productNameField = value;
                    this.RaisePropertyChanged("productName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.productCodeField, value) != true)) {
                    this.productCodeField = value;
                    this.RaisePropertyChanged("productCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string quantityInStock {
            get {
                return this.quantityInStockField;
            }
            set {
                if ((object.ReferenceEquals(this.quantityInStockField, value) != true)) {
                    this.quantityInStockField = value;
                    this.RaisePropertyChanged("quantityInStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msrp {
            get {
                return this.msrpField;
            }
            set {
                if ((object.ReferenceEquals(this.msrpField, value) != true)) {
                    this.msrpField = value;
                    this.RaisePropertyChanged("msrp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool inStore {
            get {
                return this.inStoreField;
            }
            set {
                if ((this.inStoreField.Equals(value) != true)) {
                    this.inStoreField = value;
                    this.RaisePropertyChanged("inStore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="supplierService.supplierWebServiceSoap")]
    public interface supplierWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name productCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWaitTime", ReplyAction="*")]
        warehouseService.supplierService.getWaitTimeResponse getWaitTime(warehouseService.supplierService.getWaitTimeRequest request);
        
        // CODEGEN: Generating message contract since element name orderQueue from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/restockWarehouse", ReplyAction="*")]
        warehouseService.supplierService.restockWarehouseResponse restockWarehouse(warehouseService.supplierService.restockWarehouseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWaitTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWaitTime", Namespace="http://tempuri.org/", Order=0)]
        public warehouseService.supplierService.getWaitTimeRequestBody Body;
        
        public getWaitTimeRequest() {
        }
        
        public getWaitTimeRequest(warehouseService.supplierService.getWaitTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWaitTimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productCode;
        
        public getWaitTimeRequestBody() {
        }
        
        public getWaitTimeRequestBody(string productCode) {
            this.productCode = productCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWaitTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWaitTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public warehouseService.supplierService.getWaitTimeResponseBody Body;
        
        public getWaitTimeResponse() {
        }
        
        public getWaitTimeResponse(warehouseService.supplierService.getWaitTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWaitTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getWaitTimeResult;
        
        public getWaitTimeResponseBody() {
        }
        
        public getWaitTimeResponseBody(string getWaitTimeResult) {
            this.getWaitTimeResult = getWaitTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class restockWarehouseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="restockWarehouse", Namespace="http://tempuri.org/", Order=0)]
        public warehouseService.supplierService.restockWarehouseRequestBody Body;
        
        public restockWarehouseRequest() {
        }
        
        public restockWarehouseRequest(warehouseService.supplierService.restockWarehouseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class restockWarehouseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public warehouseService.supplierService.OrderQueue[] orderQueue;
        
        public restockWarehouseRequestBody() {
        }
        
        public restockWarehouseRequestBody(warehouseService.supplierService.OrderQueue[] orderQueue) {
            this.orderQueue = orderQueue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class restockWarehouseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="restockWarehouseResponse", Namespace="http://tempuri.org/", Order=0)]
        public warehouseService.supplierService.restockWarehouseResponseBody Body;
        
        public restockWarehouseResponse() {
        }
        
        public restockWarehouseResponse(warehouseService.supplierService.restockWarehouseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class restockWarehouseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public warehouseService.supplierService.Product[] restockWarehouseResult;
        
        public restockWarehouseResponseBody() {
        }
        
        public restockWarehouseResponseBody(warehouseService.supplierService.Product[] restockWarehouseResult) {
            this.restockWarehouseResult = restockWarehouseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface supplierWebServiceSoapChannel : warehouseService.supplierService.supplierWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class supplierWebServiceSoapClient : System.ServiceModel.ClientBase<warehouseService.supplierService.supplierWebServiceSoap>, warehouseService.supplierService.supplierWebServiceSoap {
        
        public supplierWebServiceSoapClient() {
        }
        
        public supplierWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public supplierWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public supplierWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public supplierWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        warehouseService.supplierService.getWaitTimeResponse warehouseService.supplierService.supplierWebServiceSoap.getWaitTime(warehouseService.supplierService.getWaitTimeRequest request) {
            return base.Channel.getWaitTime(request);
        }
        
        public string getWaitTime(string productCode) {
            warehouseService.supplierService.getWaitTimeRequest inValue = new warehouseService.supplierService.getWaitTimeRequest();
            inValue.Body = new warehouseService.supplierService.getWaitTimeRequestBody();
            inValue.Body.productCode = productCode;
            warehouseService.supplierService.getWaitTimeResponse retVal = ((warehouseService.supplierService.supplierWebServiceSoap)(this)).getWaitTime(inValue);
            return retVal.Body.getWaitTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        warehouseService.supplierService.restockWarehouseResponse warehouseService.supplierService.supplierWebServiceSoap.restockWarehouse(warehouseService.supplierService.restockWarehouseRequest request) {
            return base.Channel.restockWarehouse(request);
        }
        
        public warehouseService.supplierService.Product[] restockWarehouse(warehouseService.supplierService.OrderQueue[] orderQueue) {
            warehouseService.supplierService.restockWarehouseRequest inValue = new warehouseService.supplierService.restockWarehouseRequest();
            inValue.Body = new warehouseService.supplierService.restockWarehouseRequestBody();
            inValue.Body.orderQueue = orderQueue;
            warehouseService.supplierService.restockWarehouseResponse retVal = ((warehouseService.supplierService.supplierWebServiceSoap)(this)).restockWarehouse(inValue);
            return retVal.Body.restockWarehouseResult;
        }
    }
}
