//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INB374.orderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customers_customerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shippingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.orderNumberField, value) != true)) {
                    this.orderNumberField = value;
                    this.RaisePropertyChanged("orderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customers_customerNumber {
            get {
                return this.customers_customerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.customers_customerNumberField, value) != true)) {
                    this.customers_customerNumberField = value;
                    this.RaisePropertyChanged("customers_customerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orderDate {
            get {
                return this.orderDateField;
            }
            set {
                if ((object.ReferenceEquals(this.orderDateField, value) != true)) {
                    this.orderDateField = value;
                    this.RaisePropertyChanged("orderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string shippingDate {
            get {
                return this.shippingDateField;
            }
            set {
                if ((object.ReferenceEquals(this.shippingDateField, value) != true)) {
                    this.shippingDateField = value;
                    this.RaisePropertyChanged("shippingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                if ((object.ReferenceEquals(this.commentsField, value) != true)) {
                    this.commentsField = value;
                    this.RaisePropertyChanged("comments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orders_orderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string quantityOrderedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string priceEachField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string orders_orderNumber {
            get {
                return this.orders_orderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.orders_orderNumberField, value) != true)) {
                    this.orders_orderNumberField = value;
                    this.RaisePropertyChanged("orders_orderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.productCodeField, value) != true)) {
                    this.productCodeField = value;
                    this.RaisePropertyChanged("productCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string quantityOrdered {
            get {
                return this.quantityOrderedField;
            }
            set {
                if ((object.ReferenceEquals(this.quantityOrderedField, value) != true)) {
                    this.quantityOrderedField = value;
                    this.RaisePropertyChanged("quantityOrdered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string priceEach {
            get {
                return this.priceEachField;
            }
            set {
                if ((object.ReferenceEquals(this.priceEachField, value) != true)) {
                    this.priceEachField = value;
                    this.RaisePropertyChanged("priceEach");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="orderService.orderWebServiceSoap")]
    public interface orderWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name order from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addOrder", ReplyAction="*")]
        INB374.orderService.addOrderResponse addOrder(INB374.orderService.addOrderRequest request);
        
        // CODEGEN: Generating message contract since element name orderDetails from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addOrderDetails", ReplyAction="*")]
        INB374.orderService.addOrderDetailsResponse addOrderDetails(INB374.orderService.addOrderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateExistingOrders", ReplyAction="*")]
        void updateExistingOrders();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addOrder", Namespace="http://tempuri.org/", Order=0)]
        public INB374.orderService.addOrderRequestBody Body;
        
        public addOrderRequest() {
        }
        
        public addOrderRequest(INB374.orderService.addOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public INB374.orderService.Order order;
        
        public addOrderRequestBody() {
        }
        
        public addOrderRequestBody(INB374.orderService.Order order) {
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public INB374.orderService.addOrderResponseBody Body;
        
        public addOrderResponse() {
        }
        
        public addOrderResponse(INB374.orderService.addOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addOrderResponseBody {
        
        public addOrderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addOrderDetails", Namespace="http://tempuri.org/", Order=0)]
        public INB374.orderService.addOrderDetailsRequestBody Body;
        
        public addOrderDetailsRequest() {
        }
        
        public addOrderDetailsRequest(INB374.orderService.addOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addOrderDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public INB374.orderService.OrderDetails orderDetails;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int quantityStocked;
        
        public addOrderDetailsRequestBody() {
        }
        
        public addOrderDetailsRequestBody(INB374.orderService.OrderDetails orderDetails, int quantityStocked) {
            this.orderDetails = orderDetails;
            this.quantityStocked = quantityStocked;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addOrderDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public INB374.orderService.addOrderDetailsResponseBody Body;
        
        public addOrderDetailsResponse() {
        }
        
        public addOrderDetailsResponse(INB374.orderService.addOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addOrderDetailsResponseBody {
        
        public addOrderDetailsResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface orderWebServiceSoapChannel : INB374.orderService.orderWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class orderWebServiceSoapClient : System.ServiceModel.ClientBase<INB374.orderService.orderWebServiceSoap>, INB374.orderService.orderWebServiceSoap {
        
        public orderWebServiceSoapClient() {
        }
        
        public orderWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public orderWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public orderWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public orderWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INB374.orderService.addOrderResponse INB374.orderService.orderWebServiceSoap.addOrder(INB374.orderService.addOrderRequest request) {
            return base.Channel.addOrder(request);
        }
        
        public void addOrder(INB374.orderService.Order order) {
            INB374.orderService.addOrderRequest inValue = new INB374.orderService.addOrderRequest();
            inValue.Body = new INB374.orderService.addOrderRequestBody();
            inValue.Body.order = order;
            INB374.orderService.addOrderResponse retVal = ((INB374.orderService.orderWebServiceSoap)(this)).addOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INB374.orderService.addOrderDetailsResponse INB374.orderService.orderWebServiceSoap.addOrderDetails(INB374.orderService.addOrderDetailsRequest request) {
            return base.Channel.addOrderDetails(request);
        }
        
        public void addOrderDetails(INB374.orderService.OrderDetails orderDetails, int quantityStocked) {
            INB374.orderService.addOrderDetailsRequest inValue = new INB374.orderService.addOrderDetailsRequest();
            inValue.Body = new INB374.orderService.addOrderDetailsRequestBody();
            inValue.Body.orderDetails = orderDetails;
            inValue.Body.quantityStocked = quantityStocked;
            INB374.orderService.addOrderDetailsResponse retVal = ((INB374.orderService.orderWebServiceSoap)(this)).addOrderDetails(inValue);
        }
        
        public void updateExistingOrders() {
            base.Channel.updateExistingOrders();
        }
    }
}
